name = "Phi 4 Mini 3.8B"
description = "Phi 4 Mini is optimized for use in lightweight environments, excelling at quick interactions, and constrained-resource deployments. It supports strong mathematical and logical inference, suitable for embedded applications, mobile environments, or real-time AI assistants."
family = "phi"
release_date = "2025-02-01"
last_updated = "2025-02-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2023-10"
open_weights = true

[cost]
input = 0.08
output = 0.35
cache_read = 0.08

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
