# Source: https://routellm.abacus.ai/v1/models
base_model = "minimax/MiniMax-M3"
reasoning_options = []

[cost]
input = 0.3
output = 1.2

[limit]
context = 1_000_000
output = 131_072

[modalities]
input = ["text", "image", "video"]
output = ["text"]
