// Generated by script/generate.ts. Do not edit; run `bun run generate` in packages/sdk.

/** Provider IDs known when this SDK version was generated. Newer providers may exist; the API is the source of truth. */
export const KNOWN_PROVIDER_IDS = [
  "302ai",
  "abacus",
  "abliteration-ai",
  "aihubmix",
  "alibaba",
  "alibaba-cn",
  "alibaba-coding-plan",
  "alibaba-coding-plan-cn",
  "alibaba-token-plan",
  "alibaba-token-plan-cn",
  "amazon-bedrock",
  "ambient",
  "anthropic",
  "anyapi",
  "atomic-chat",
  "auriko",
  "azure",
  "azure-cognitive-services",
  "bailing",
  "baseten",
  "berget",
  "cerebras",
  "chutes",
  "clarifai",
  "claudinio",
  "cloudferro-sherlock",
  "cloudflare-ai-gateway",
  "cloudflare-workers-ai",
  "cohere",
  "cortecs",
  "crof",
  "databricks",
  "deepinfra",
  "deepseek",
  "digitalocean",
  "dinference",
  "drun",
  "evroc",
  "fastrouter",
  "fireworks-ai",
  "freemodel",
  "friendli",
  "frogbot",
  "github-copilot",
  "github-models",
  "gitlab",
  "gmicloud",
  "google",
  "google-vertex",
  "google-vertex-anthropic",
  "groq",
  "helicone",
  "hpc-ai",
  "huggingface",
  "iflowcn",
  "inception",
  "inceptron",
  "inference",
  "io-net",
  "jiekou",
  "kilo",
  "kimi-for-coding",
  "kuae-cloud-coding-plan",
  "lilac",
  "llama",
  "llmgateway",
  "llmtr",
  "lmstudio",
  "lucidquery",
  "meganova",
  "merge-gateway",
  "minimax",
  "minimax-cn",
  "minimax-cn-coding-plan",
  "minimax-coding-plan",
  "mistral",
  "mixlayer",
  "moark",
  "modelscope",
  "moonshotai",
  "moonshotai-cn",
  "morph",
  "nano-gpt",
  "nearai",
  "nebius",
  "neon",
  "neuralwatt",
  "nova",
  "novita-ai",
  "nvidia",
  "ollama-cloud",
  "openai",
  "opencode",
  "opencode-go",
  "openrouter",
  "orcarouter",
  "ovhcloud",
  "perplexity",
  "perplexity-agent",
  "poe",
  "poolside",
  "privatemode-ai",
  "qihang-ai",
  "qiniu-ai",
  "regolo-ai",
  "requesty",
  "routing-run",
  "sakana",
  "sap-ai-core",
  "sarvam",
  "scaleway",
  "siliconflow",
  "siliconflow-cn",
  "snowflake-cortex",
  "stackit",
  "stepfun",
  "stepfun-ai",
  "subconscious",
  "submodel",
  "synthetic",
  "tencent-coding-plan",
  "tencent-tokenhub",
  "the-grid-ai",
  "tinfoil",
  "togetherai",
  "umans-ai",
  "umans-ai-coding-plan",
  "upstage",
  "v0",
  "venice",
  "vercel",
  "vivgrid",
  "vultr",
  "wafer.ai",
  "wandb",
  "xai",
  "xiaomi",
  "xiaomi-token-plan-ams",
  "xiaomi-token-plan-cn",
  "xiaomi-token-plan-sgp",
  "xpersona",
  "zai",
  "zai-coding-plan",
  "zeldoc",
  "zenmux",
  "zhipuai",
  "zhipuai-coding-plan",
] as const

export type KnownProviderID = (typeof KNOWN_PROVIDER_IDS)[number]

/** Model family identifiers used to group related models. */
export type ModelFamily =
  | "Hy"
  | "agi"
  | "allam"
  | "allenai"
  | "alpha"
  | "aura"
  | "auto"
  | "baichuan"
  | "bart"
  | "bge"
  | "big-pickle"
  | "canopylabs"
  | "chutesai"
  | "claude"
  | "claude-fable"
  | "claude-haiku"
  | "claude-opus"
  | "claude-sonnet"
  | "codestral"
  | "codestral-embed"
  | "cogito"
  | "cohere-embed"
  | "command"
  | "command-a"
  | "command-light"
  | "command-r"
  | "dall-e"
  | "deepseek"
  | "deepseek-flash"
  | "deepseek-flash-free"
  | "deepseek-flash-think"
  | "deepseek-thinking"
  | "devstral"
  | "discolm"
  | "distilbert"
  | "dream-machine"
  | "dreamshaper"
  | "elephant"
  | "elevenlabs"
  | "ernie"
  | "falcon"
  | "flux"
  | "fugu"
  | "gemini"
  | "gemini-embedding"
  | "gemini-flash"
  | "gemini-flash-lite"
  | "gemini-pro"
  | "gemma"
  | "glm"
  | "glm-air"
  | "glm-flash"
  | "glm-free"
  | "glm-z"
  | "glmv"
  | "gpt"
  | "gpt-codex"
  | "gpt-codex-mini"
  | "gpt-codex-spark"
  | "gpt-image"
  | "gpt-mini"
  | "gpt-nano"
  | "gpt-oss"
  | "gpt-pro"
  | "granite"
  | "grok"
  | "grok-beta"
  | "grok-build"
  | "grok-vision"
  | "groq"
  | "hermes"
  | "hunyuan"
  | "hy3"
  | "hy3-free"
  | "ideogram"
  | "imagen"
  | "indictrans"
  | "intellect"
  | "jais"
  | "jamba"
  | "kat-coder"
  | "kimi"
  | "kimi-free"
  | "kimi-k2"
  | "kimi-thinking"
  | "ling"
  | "ling-flash-free"
  | "liquid"
  | "llama"
  | "llava"
  | "longcat"
  | "lucid"
  | "lyria"
  | "m2m"
  | "magistral"
  | "magistral-medium"
  | "magistral-small"
  | "mai"
  | "melotts"
  | "mercury"
  | "mimo"
  | "mimo-flash-free"
  | "mimo-omni"
  | "mimo-omni-free"
  | "mimo-pro"
  | "mimo-pro-free"
  | "mimo-v2-omni"
  | "mimo-v2-pro"
  | "mimo-v2.5"
  | "mimo-v2.5-free"
  | "mimo-v2.5-pro"
  | "minimax"
  | "minimax-free"
  | "minimax-m2.5"
  | "minimax-m2.7"
  | "minimax-m3"
  | "minimax-m3-free"
  | "ministral"
  | "mistral"
  | "mistral-embed"
  | "mistral-large"
  | "mistral-medium"
  | "mistral-nemo"
  | "mistral-small"
  | "mixtral"
  | "mm-poly"
  | "model-router"
  | "morph"
  | "nano-banana"
  | "nemoretriever"
  | "nemotron"
  | "nemotron-free"
  | "neural-chat"
  | "north"
  | "north-free"
  | "nousresearch"
  | "nova"
  | "nova-lite"
  | "nova-micro"
  | "nova-pro"
  | "o"
  | "o-mini"
  | "o-pro"
  | "openchat"
  | "opengvlab"
  | "ornith"
  | "osmosis"
  | "oswe"
  | "palmyra"
  | "pangu"
  | "parakeet"
  | "phi"
  | "phoenix"
  | "pixtral"
  | "plamo"
  | "pony"
  | "qvq"
  | "qwen"
  | "qwen-free"
  | "qwen3.5"
  | "qwen3.6"
  | "qwen3.7-max"
  | "qwen3.7-plus"
  | "qwerky"
  | "ray"
  | "recraft"
  | "rednote"
  | "reka"
  | "resnet"
  | "ring"
  | "ring-1t-free"
  | "rnj"
  | "runway"
  | "sarvam"
  | "seed"
  | "sherlock"
  | "skywork"
  | "smart-turn"
  | "solar"
  | "solar-mini"
  | "solar-pro"
  | "sonar"
  | "sonar-deep-research"
  | "sonar-pro"
  | "sonar-reasoning"
  | "sora"
  | "sourceful"
  | "sqlcoder"
  | "stable-diffusion"
  | "starling"
  | "step"
  | "tako"
  | "text-embedding"
  | "titan"
  | "titan-embed"
  | "tngtech"
  | "topazlabs"
  | "trinity"
  | "trinity-mini"
  | "tstars"
  | "una-cybertron"
  | "unsloth"
  | "v0"
  | "venice"
  | "veo"
  | "voxtral"
  | "voyage"
  | "whisper"
  | "yi"
  | "zephyr"
