base_model = "minimax/MiniMax-M2.5"
name = "MiniMax M2.5"
description = "MiniMax M2.5 is a Mixture-of-Experts (MoE) model featuring 230 billion total parameters and 10 billion active parameters per token during inference. This highly sparse architecture allows for high-throughput and low-latency with strong coding capabilities."
family = "minimax-m2.5"
structured_output = true
reasoning_options = []

[cost]
input = 0.3
output = 1.2
cache_read = 0.3

[limit]
context = 196_608
output = 196_608
