name = "mistralai--mistral-large-instruct"
description = "mistralai--mistral-large-instruct"
release_date = "2026-07-14"
last_updated = "2026-07-14"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 1.12
output = 3.2

[limit]
context = 131072
output = 4096

[modalities]
input = ["text"]
output = ["text"]
