# Source: https://routellm.abacus.ai/v1/models
base_model = "meta/llama-4-maverick-17b-instruct"
reasoning = false

[cost]
input = 0.14
output = 0.59

[limit]
context = 1_048_576
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
