# Source: https://routellm.abacus.ai/v1/models
base_model = "anthropic/claude-haiku-4-5-20251001"
reasoning = true
reasoning_options = []

[cost]
input = 1.00
output = 5.00

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image"]
output = ["text"]
