# Source: https://routellm.abacus.ai/v1/models
base_model = "google/gemini-2.5-pro"
reasoning = true
reasoning_options = []

[cost]
input = 1.25
output = 10.00
cache_read = 0.125

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "audio"]
output = ["text"]
