base_model = "openai/o3-pro"
reasoning = true
reasoning_options = []

[cost]
input = 20.00
output = 40.00

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image"]
output = ["text"]
