base_model = "openai/o4-mini"
reasoning = true
reasoning_options = []

[cost]
input = 1.1
output = 4.4

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image"]
output = ["text"]
